### ISSUE TITLE
Avoid empty loop on ESP 

### ISSUE THREAD

**Issue by NicHub** [SensorsIot/Hacking-433#1]
Hi Andreas,

Thank you for sharing [your RF433 hacks on YouTube](https://www.youtube.com/watch?v=L0fSEbGEY-Q) and here.

I was reading your code `Awning_Control_ESP32.ino` and I stumbled upon the empty `void loop(){}`. I didn’t test your code, but you should definitely avoid looping without a `delay` or a `yield` command on the ESP8266, otherwise it will crash pretty soon. I guess this is also valid for the ESP32 though I only have experience with the ESP8266.

So you should modify your main loop like that:

	void loop() { yield(); }

or like that:

	void loop() { delay(1); }

**Comment by SensorsIot** [comment]
The ESP32 does not have this issue.
